model_name=DUET
batch_size=32
d_ff=512
factor=3
lradj='type1'
num_experts=4
patience=5
patch_len=48
d_model=512

python3 -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_512_96 \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 512 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 1 \
  --d_layers 1 \
  --d_model $d_model \
  --d_ff $d_ff \
  --hidden_size 256 \
  --n_heads 1 \
  --seg_len 6 \
  --win_size 2\
  --activation 'gelu' \
  --patch_len $patch_len \
  --stride 8 \
  --period_len 4 \
  --dropout 0.5 \
  --fc_dropout 0.1 \
  --moving_avg 25 \
  --lradj $lradj \
  --batch_size $batch_size \
  --learning_rate 0.0005  \
  --train_epochs 100 \
  --loss 'MAE' \
  --patience $patience \
  --num_experts 2 \
  --noisy_gating \
  --k 1 \
  --CI \
  --factor $factor \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1

python3 -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_336_192 \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 336 \
  --label_len 48 \
  --pred_len 192 \
  --d_model $d_model \
  --d_ff $d_ff \
  --hidden_size 256 \
  --n_heads 1 \
  --seg_len 6 \
  --win_size 2\
  --activation 'gelu' \
  --patch_len $patch_len \
  --stride 8 \
  --period_len 4 \
  --dropout 0.5 \
  --fc_dropout 0.1 \
  --moving_avg 25 \
  --lradj $lradj \
  --batch_size 64 \
  --learning_rate 0.0005  \
  --train_epochs 100 \
  --loss 'MAE' \
  --patience $patience \
  --num_experts $num_experts \
  --noisy_gating \
  --k 2 \
  --CI \
  --e_layers 1 \
  --d_layers 1 \
  --factor $factor \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1

python3 -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_512_336 \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 512 \
  --label_len 48 \
  --pred_len 336 \
  --d_model $d_model \
  --d_ff 1024 \
  --hidden_size 256 \
  --n_heads 2 \
  --seg_len 6 \
  --win_size 2\
  --activation 'gelu' \
  --patch_len $patch_len \
  --stride 8 \
  --period_len 4 \
  --dropout 0.4 \
  --fc_dropout 0.05 \
  --moving_avg 25 \
  --lradj $lradj \
  --batch_size 128 \
  --learning_rate 0.0001  \
  --train_epochs 100 \
  --loss 'MAE' \
  --patience $patience \
  --num_experts $num_experts \
  --noisy_gating \
  --k 3 \
  --CI \
  --e_layers 1 \
  --d_layers 1 \
  --factor $factor \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1

python3 -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_512_720 \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 512 \
  --label_len 48 \
  --pred_len 720 \
  --d_model $d_model \
  --d_ff $d_ff \
  --hidden_size 256 \
  --n_heads 1 \
  --seg_len 6 \
  --win_size 2\
  --activation 'gelu' \
  --patch_len $patch_len \
  --stride 8 \
  --period_len 4 \
  --dropout 0.2 \
  --fc_dropout 0.1 \
  --moving_avg 25 \
  --lradj $lradj \
  --batch_size $batch_size \
  --learning_rate 0.0005  \
  --train_epochs 100 \
  --loss 'MAE' \
  --patience $patience \
  --num_experts $num_experts \
  --noisy_gating \
  --k 2 \
  --CI \
  --e_layers 2 \
  --d_layers 1 \
  --factor $factor \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1
