python3 -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/nyse/ \
  --data_path nyse.csv \
  --model_id nyse_48_24 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len $seq_len \
  --label_len 48 \
  --pred_len 24 \
  --e_layers $e_layers \
  --d_layers 1 \
  --factor 3 \
  --enc_in 5 \
  --dec_in 5 \
  --c_out 5 \
  --des 'Exp' \
  --itr 1 \
  --down_sampling_layers 3 \
  --down_sampling_method avg \
  --down_sampling_window 2 \
  --d_model $d_model \
  --d_ff $d_ff \
  --train_epochs $train_epochs \
  --loss $loss \
  --learning_rate $learning_rate \
  --lradj $lradj


python3 -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/nyse/ \
  --data_path nyse.csv \
  --model_id nyse_48_36 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len $seq_len \
  --label_len 48 \
  --pred_len 36 \
  --e_layers $e_layers \
  --d_layers 1 \
  --factor 3 \
  --enc_in 5 \
  --dec_in 5 \
  --c_out 5 \
  --des 'Exp' \
  --itr 1 \
  --down_sampling_layers 3 \
  --down_sampling_method avg \
  --down_sampling_window 2 \
  --d_model $d_model \
  --d_ff $d_ff \
  --train_epochs $train_epochs \
  --loss $loss \
  --learning_rate $learning_rate \
  --lradj $lradj

python3 -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/nyse/ \
  --data_path nyse.csv \
  --model_id nyse_48_48 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len $seq_len \
  --label_len 48 \
  --pred_len 48 \
  --e_layers $e_layers \
  --d_layers 1 \
  --factor 3 \
  --enc_in 5 \
  --dec_in 5 \
  --c_out 5 \
  --des 'Exp' \
  --itr 1 \
  --down_sampling_layers 3 \
  --down_sampling_method avg \
  --down_sampling_window 2 \
  --d_model $d_model \
  --d_ff $d_ff \
  --train_epochs $train_epochs \
  --loss $loss \
  --learning_rate $learning_rate \
  --lradj $lradj

python3 -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/nyse/ \
  --data_path nyse.csv \
  --model_id nyse_48_60 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len $seq_len \
  --label_len 48 \
  --pred_len 60 \
  --e_layers $e_layers \
  --d_layers 1 \
  --factor 3 \
  --enc_in 5 \
  --dec_in 5 \
  --c_out 5 \
  --des 'Exp' \
  --itr 1 \
  --down_sampling_layers 3 \
  --down_sampling_method avg \
  --down_sampling_window 2 \
  --d_model $d_model \
  --d_ff $d_ff \
  --train_epochs $train_epochs \
  --loss $loss \
  --learning_rate $learning_rate \
  --lradj $lradj